### ISSUE TITLE
Unexpected behavior - zoom/rotation

### ISSUE THREAD

**Issue by SimonKufeld** [FelixAhrens/CameraX-ImageAnalysis-Beta06-Java-TFLite-ObjectDetection#1]
I noticed a few things in the context of zooming/rotating. In the case of zooming, the zoom level above the seekbar disappears. Additionally, when rotating the device, the slider stays at the zoom position, but the zoom level resets to its original value.

**Comment by FelixAhrens** [comment]
Thanks for the hint.  I'll take a look at it.

**Comment by FelixAhrens** [comment]
It's fixed, thanks again for your help!
