### ISSUE TITLE
neural style transfer

### ISSUE THREAD

**Issue by maylad31** [FelixAhrens/CameraX-ImageAnalysis-Beta06-Java-TFLite-ObjectDetection#2]
hi,it is not an issue with your code. Just that i want to run neural style transfer. I am new to android and your code seems a good starting point. My input is bgr image. I get i can change that at convertBitmapToByteBuffer where you put rgb values if i am correct. Can you just guide me how do i show the output of my model using cameraX. My output is also a bgr image and i need to apply normalization. Thanks.

**Comment by FelixAhrens** [comment]
Hey, I'm glad to hear you want to use my code. Unfortunately, I never worked with BGR Color space. But I would guess that you have to start at the toBitmap() function. There the image gets convert to an Bitmap in the first place.

**Comment by maylad31** [comment]
okay, thanks, i thought imgData.put((byte) ((val >> 16) & 0xFF));
                    imgData.put((byte) ((val >> 8) & 0xFF));
                    imgData.put((byte) (val & 0xFF)); here you put rgb values into buffer.
